baseURL = 'https://rajnoor.info/'
languageCode = 'en-us'
title = 'Rajnoor'
disableKinds = ["taxonomy", "term"]
[outputs]
  home = ["html"]
  section = ["html"]
  page = ["html"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Needed to allow raw HTML inside Markdown

[params]
  math = true  # Enables math rendering